### ISSUE TITLE
Conversation starts with wrong contact

### ISSUE THREAD

**Issue by T1m1** [locator-kn/web#103]
I clicked to "start conversation" on my trip in trip overview (search result view). 
![bug_start_message_2](https://cloud.githubusercontent.com/assets/5616884/8541156/5a30aa10-248c-11e5-8e8c-f7e05cc8d93a.JPG)

The message appeared in another conversation:

![bug_start_message](https://cloud.githubusercontent.com/assets/5616884/8541176/80f1e1c8-248c-11e5-8d92-b4cb03dece3b.JPG)

**Comment by timoweiss** [comment]
@NicolaiLoeffler maybe the wrong id is supplied... The route param is named mistakably `opponentId` which is actually the conversation id.
