### ISSUE TITLE
emoji section

### ISSUE THREAD

**Issue by michaelknoch** [locator-kn/web#105]
Wir benötigen ein emoji icon und am besten ein Design für das Emoji Popover.

![bildschirmfoto 2015-07-07 um 11 04 30](https://cloud.githubusercontent.com/assets/5617793/8542709/dbc62932-2497-11e5-84c4-b892cb93573d.png)

![bildschirmfoto 2015-07-07 um 11 05 00](https://cloud.githubusercontent.com/assets/5617793/8542731/eea00276-2497-11e5-89cb-f48715eec5fb.png)

**Comment by loptik** [comment]
![emoji-54-54](https://cloud.githubusercontent.com/assets/12908463/8634805/c7f5ca48-2807-11e5-969b-f442d37058d6.png)
