### ISSUE TITLE
Schwarzer Balken bei der Slideshow

### ISSUE THREAD

**Issue by loptik** [locator-kn/web#119]
kann man den schwarzen balken, indem sich der pfeil befindet noch so ingesamt 10 px breiter machen? das dreieck klebt da so drin
<img width="595" alt="bildschirmfoto 2015-07-10 um 16 44 08" src="https://cloud.githubusercontent.com/assets/12908463/8620933/0b775952-2723-11e5-8c8b-811cfd03cae6.png">

**Comment by michaelknoch** [comment]
das problem hast du schon selber gelöst, da du die svgs mit mehr space angelegt hast. passt das so?

**Comment by tschulo** [comment]
passt so :) - closed
