### ISSUE TITLE
After I create a trip, I can't find it in "my trips"

### ISSUE THREAD

**Issue by T1m1** [locator-kn/web#126]
My trip:

![image](https://cloud.githubusercontent.com/assets/5616884/8633503/58fd8daa-27cc-11e5-852a-9497fa945445.png)

"my trips view":

![image](https://cloud.githubusercontent.com/assets/5616884/8633499/38a07964-27cc-11e5-9860-2fb17bc76011.png)

**Comment by SteffenGorenflo** [comment]
was sagt der request? immer gleich checken und mit angeben bitte! Kanns bei mir nich nachvollziehen

**Comment by T1m1** [comment]
![image](https://cloud.githubusercontent.com/assets/5616884/8633541/a35f405e-27cd-11e5-9a04-b819d5943e1c.png)

Wird glaub anstatt den Trips nur die Locations requestet.
Obwohl in der URL trips steht :
http://locator-app.com/develop/#/user/05888095f626a4afb3b11568acdc9f90?tab=trips

**Comment by timoweiss** [comment]
fixed
