### ISSUE TITLE
Hide date text in create trip 'preview', if no date is selected

### ISSUE THREAD

**Issue by T1m1** [locator-kn/web#128]
![image](https://cloud.githubusercontent.com/assets/5616884/8633517/dc08cba6-27cc-11e5-9abe-2fc462c0d065.png)

**Comment by SteffenGorenflo** [comment]
![image](https://cloud.githubusercontent.com/assets/5612074/8633547/d42809f0-27cd-11e5-9a46-32a176e8e3a9.png)

**Comment by T1m1** [comment]
Da ging es aber um die Trip-Ansicht.. nicht preview

**Comment by SteffenGorenflo** [comment]
is dochs gleiche problem

**Comment by T1m1** [comment]
Aber andere Views. Das "bis" wurde ja auch noch angezeigt.. und in der Suche nicht mehr
