### ISSUE TITLE
Feedback if user adds location which is not in a city we support right now!

### ISSUE THREAD

**Issue by timoweiss** [locator-kn/web#139]
How and when do we want to do this? @michaelknoch @loptik

**Comment by loptik** [comment]
if link to locations not possible, kill last sentence or write "du kannst alle deine locations in deinem profil anschauen"

![location_not_in_city](https://cloud.githubusercontent.com/assets/12908463/8639957/a5f1af44-28e7-11e5-808b-7cb376626fd9.jpg)
