### ISSUE TITLE
Add and Redesign Emojis für Chat

### ISSUE THREAD

**Issue by loptik** [locator-kn/web#143]
width: chatframe, height: 150 px, maybe less. (100px?). Scrollbar style like "select locations"

![locator_screens](https://cloud.githubusercontent.com/assets/12908463/8668462/8c8c8068-2a0b-11e5-9baf-3fea357aa57f.jpg)

**Comment by T1m1** [comment]
Can we allow less icons? Becaus there are to many icons to handle in mobile at the moment.

**Comment by timoweiss** [comment]
I think its also bloated for web

**Comment by loptik** [comment]
that is just an example. it can be smaller and with less emojs
