### ISSUE TITLE
Container layout, screen width >750px & <1000px

### ISSUE THREAD

**Issue by NicolaiLoeffler** [locator-kn/web#146]
Wie wollen wir das handeln, der content ist zu groß bei diesen screen größen. Container höher, accomodation icons kleiner?

**Comment by NicolaiLoeffler** [comment]
<img width="707" alt="screen" src="https://cloud.githubusercontent.com/assets/5612127/8679659/4904fb44-2a5c-11e5-97ed-aa3717792dcf.png">

**Comment by michaelknoch** [comment]
eine möglichkeit wäre auch die infobox breiter zu machen.  Also anstatt Slider 8 infobox 4 --> Slider 7 Infobox 5
