### ISSUE TITLE
Welcome Mail New Text

### ISSUE THREAD

**Issue by loptik** [locator-kn/web#151]
Add new Welcome Text to Welcome Mail

Herzlich Willkommen bei LOCATOR und vielen Dank für deine Anmeldung.

LOCATOR befindet sich derzeit noch in einer BETA-Phase.
Deshalb kannst vorerst nur Trips im Raum Konstanz erstellen.
Du kannst aber deine Lieblings-Locations überall auf der Welt spotten und fleißig sammeln.
In Kürze werden wir auch in deiner Stadt sein und du kannst Trips mit deinen Locations erstellen.

Bis dahin wünschen wir dir jede Menge spannende Kurztrips und hoffentlich auch ein paar neue Bekanntschaften. 

Wir versuchen LOCATOR ständig zu verbessern und interessieren uns sehr für deine Meinung.
Wenn du willst, kannst du uns hier\* ein kleines Feedback schreiben.

Wir wünschen dir viel Spaß mit LOCATOR und einen wunderschönen Tag

Dein LOCATOR-Team

*Link to Feedbackfieldon Website

**Comment by SteffenGorenflo** [comment]
Die Mail kommt, wenn man sich ab Samstag bei uns anmeldet oder wenn man sich auf der Projekt seite registriert? Sollen wir ein Link einfügen á la "Hier auf den Link klicken um deine E-mail adresse zu verifizieren"
