### ISSUE TITLE
broken ui

### ISSUE THREAD

**Issue by timoweiss** [locator-kn/web#161]
![screen shot 2015-07-18 at 1 43 00 am](https://cloud.githubusercontent.com/assets/5221667/8759133/7449fa36-2cee-11e5-97fd-6d941ccbfbfc.png)
![screen shot 2015-07-18 at 1 43 11 am](https://cloud.githubusercontent.com/assets/5221667/8759154/c1447f46-2cee-11e5-89ed-a7d7588bfa59.png)

**Comment by NicolaiLoeffler** [comment]
bug in lower screen is fixed
