### ISSUE TITLE
facebook/google user icons don't displayed in chat header

### ISSUE THREAD

**Issue by T1m1** [locator-kn/web#178]
![image](https://cloud.githubusercontent.com/assets/5616884/8847004/57ffc374-312b-11e5-8232-fdb3d04a9e24.png)

![image](https://cloud.githubusercontent.com/assets/5616884/8847014/67d026cc-312b-11e5-8146-2221e78c5cf6.png)

**Comment by timoweiss** [comment]
https://github.com/locator-kn/web/commit/856f2a2

**Comment by SteffenGorenflo** [comment]
fixed?

**Comment by timoweiss** [comment]
fixed
