### ISSUE TITLE
location image größe

### ISSUE THREAD

**Issue by michaelknoch** [locator-kn/web#179]
Ich finde der angezeigte Bildausschnitt passt null auf die von uns definierten Bildmaße beim Upload.
Machen wir das Bild bitte größer? 70/80/90% von der Bildschirmhöhe könnte ich mir vorstellen.

derzeit:
![bildschirmfoto 2015-07-23 um 22 57 07](https://cloud.githubusercontent.com/assets/5617793/8862067/35eeee6e-318e-11e5-8fca-619d32e56886.jpg)

so stell ich mir das vor:
![bildschirmfoto 2015-07-23 um 22 57 02](https://cloud.githubusercontent.com/assets/5617793/8862068/39e715be-318e-11e5-9ef6-516706a9599c.jpg)

**Comment by T1m1** [comment]
Und evtl. auch anklickbar machen, dass ein Vollbild erscheint

**Comment by michaelknoch** [comment]
auf ein 100% x 80% bild muss ich dann auch nicht mehr klicken :smile: , aber ich lass mich gerne überzeugen.

**Comment by timoweiss** [comment]
:+1: für größere bilder

**Comment by T1m1** [comment]
Ich möchte schon irgendwo das gesammte Bild sehen können :)

**Comment by timoweiss** [comment]
jo, das ist dann aber eine größere Änderung. Für größere Bilder müssen wir im Idealfall nur eine CSS prop ändern :)

**Comment by T1m1** [comment]
Dann hau ich meinen Wunsch ins brainstorm :)

**Comment by timoweiss** [comment]
@loptik @tschulo was sagt ihr?

**Comment by tschulo** [comment]
find ich schick :)

**Comment by loptik** [comment]
ich auch. kann man so machen

**Comment by michaelknoch** [comment]
Done
