### ISSUE TITLE
seo

### ISSUE THREAD

**Issue by michaelknoch** [locator-kn/web#185]
"At Friday, May 23, 2014 at 9:00 AM, Google announced that they're finally crawling javascript. Not like before, unpredictable and on minimal scale, no. The whole thing."

https://github.com/steeve/angular-seo
http://www.ng-newsletter.com/posts/serious-angular-seo.html
https://weluse.de/blog/angularjs-seo-finally-a-piece-of-cake.html
https://builtvisible.com/javascript-framework-seo/

**Comment by SteffenGorenflo** [comment]
woop woop

**Comment by SteffenGorenflo** [comment]
https://www.google.com/webmasters/tools/dashboard?hl=de&siteUrl=https://locator-app.com/&authuser=0

**Comment by SteffenGorenflo** [comment]
https://github.com/locator-kn/web/issues/197

and 

https://github.com/locator-kn/web/issues/196

**Comment by timoweiss** [comment]
fixed, using prerender.io for now
