### ISSUE TITLE
Insert Trip - Datepicker

### ISSUE THREAD

**Issue by T1m1** [locator-kn/web#27]
It is not possible to select only one day.

**Comment by timoweiss** [comment]
It is, if you click twice on a single day. :smile: 
Does the backend allow a trip with only a start date?

**Comment by T1m1** [comment]
Ahhhh okay, nice ;)
No, but I think it should be possible without klicking twice.. it isn't intuitive..
If the user have selected one day, and want to save... then end_date = start_date.

**Comment by timoweiss** [comment]
Should be possible @DennisMoosmann

**Comment by DennisMoosmann** [comment]
Possible now!
