### ISSUE TITLE
I get no respone if I save a location

### ISSUE THREAD

**Issue by T1m1** [locator-kn/web#49]

**Comment by timoweiss** [comment]
Discussion:
- What should happen after successful action?
- What would you guys expect?

**Comment by T1m1** [comment]
Maybe a popup/modal and then:
- stay on page or switch to page 'my locations'

**Comment by timoweiss** [comment]
@locator-kn/owners pls comment

**Comment by DennisMoosmann** [comment]
a modal should appear and you should keep staying on the 'location' page
