### ISSUE TITLE
Don't show "edit" button when viewing locations or trips

### ISSUE THREAD

**Issue by SteffenGorenflo** [locator-kn/web#54]

**Comment by T1m1** [comment]
I think it is okay to show the edit button. You can click to 'edit' and then to a location or a trip to edit your locations/trips.

**Comment by SteffenGorenflo** [comment]
In that case, display the edit button near to the trips/locations not near the name

**Comment by timoweiss** [comment]
I would offer the edit functionality in the detail view of a trip/location. (maybe additionally if you hover a listed trip/location, eg. with fading in controls)
