### ISSUE TITLE
input of textfields must be limited

### ISSUE THREAD

**Issue by T1m1** [locator-kn/web#57]
It is possible to enter infinitive letters in textfields like username, trip-title, description, ... it must be limited or handled by frontend. (maybe in backend, too)

**Comment by T1m1** [comment]
example:

[![Gyazo](http://i.gyazo.com/a19facc3709ae6dad22e7a770858009e.png)](http://gyazo.com/a19facc3709ae6dad22e7a770858009e)

**Comment by timoweiss** [comment]
very long strings should be cropped by css
