### ISSUE TITLE
tags bei locations // rundheit

### ISSUE THREAD

**Issue by tschulo** [locator-kn/web#84]
<img width="986" alt="bildschirmfoto 2015-07-06 um 10 56 04" src="https://cloud.githubusercontent.com/assets/12935497/8518802/aa015fc2-23cd-11e5-8539-3c878eed2c8a.png">

die ecken der tags bei der location-ansicht muss so rund sein, wie bei den anderen tags

**Comment by timoweiss** [comment]
@tschulo soll der border-radius ebenfalls (wie überall) 3px sein?
![screen shot 2015-07-06 at 7 09 59 pm](https://cloud.githubusercontent.com/assets/5221667/8528336/c9ed9360-2412-11e5-805a-17d08973d91a.png)
