### ISSUE TITLE
abstand zum header überall gleich

### ISSUE THREAD

**Issue by tschulo** [locator-kn/web#90]
bitte den abstand nach oben wie auf dem bild bzw. wie bei trip erstellen:
<img width="702" alt="bildschirmfoto 2015-07-06 um 11 31 30" src="https://cloud.githubusercontent.com/assets/12935497/8519370/98a135a4-23d2-11e5-88a5-ab4ae6eb3392.png">

**Comment by timoweiss** [comment]
@michaelknoch kannst du das für search fixen und auch in bs container fetzen?
