### ISSUE TITLE
position der auswahlbuttons

### ISSUE THREAD

**Issue by tschulo** [locator-kn/web#91]
können wir die buttons (tage, mood, stadt) überall gleich positionieren?

<img width="1680" alt="bildschirmfoto 2015-07-06 um 11 32 56" src="https://cloud.githubusercontent.com/assets/12935497/8519398/cde4c8e8-23d2-11e5-892d-d8e6beab48b6.png">
<img width="1680" alt="bildschirmfoto 2015-07-06 um 11 32 45" src="https://cloud.githubusercontent.com/assets/12935497/8519399/ce087482-23d2-11e5-9afe-77f77674a016.png">

**Comment by timoweiss** [comment]
related #88
