### ISSUE TITLE
abstand bei locations auswählen

### ISSUE THREAD

**Issue by tschulo** [locator-kn/web#96]
<img width="30" alt="bildschirmfoto 2015-07-06 um 12 40 19" src="https://cloud.githubusercontent.com/assets/12935497/8520628/4ee644b8-23dc-11e5-9f0b-37793187fd5c.png">
<img width="148" alt="bildschirmfoto 2015-07-06 um 12 40 35" src="https://cloud.githubusercontent.com/assets/12935497/8520630/4f094aee-23dc-11e5-8bc2-9e8ca8239cd1.png">
<img width="423" alt="bildschirmfoto 2015-07-06 um 12 40 14" src="https://cloud.githubusercontent.com/assets/12935497/8520629/4ef2b180-23dc-11e5-82da-bd43cdfd775f.png">

der rand nach rechts ist nicht schick
entweder nach links auch nen rand, oder rechts weg machen :)

**Comment by michaelknoch** [comment]
der rand rechts kommt von der scrollbar. habe ihn links angepasst.
